
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.8
  creationTimestamp: null
  name: zones.crds.kubeflare.io
spec:
  group: crds.kubeflare.io
  names:
    kind: Zone
    listKind: ZoneList
    plural: zones
    singular: zone
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Zone is the Schema for the zones API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ZoneSpec defines the desired state of Zone
          properties:
            apiToken:
              type: string
            settings:
              properties:
                advancedDDOS:
                  type: boolean
                alwaysOnline:
                  type: boolean
                alwaysUseHttps:
                  type: boolean
                automaticHTTSRewrites:
                  type: boolean
                brotli:
                  type: boolean
                browserCacheTTL:
                  type: integer
                browserCheck:
                  type: boolean
                cacheLevel:
                  type: string
                challengeTTL:
                  type: integer
                developmentMode:
                  type: boolean
                emailObfuscation:
                  type: boolean
                hotlinkProtection:
                  type: boolean
                ipGeolocation:
                  type: boolean
                ipv6:
                  type: boolean
                minify:
                  properties:
                    css:
                      type: boolean
                    html:
                      type: boolean
                    js:
                      type: boolean
                  type: object
                mirage:
                  type: boolean
                mobileRedirect:
                  properties:
                    mobileSubdomain:
                      type: string
                    status:
                      type: boolean
                    stripURI:
                      type: boolean
                  required:
                  - status
                  type: object
                opportunisticEncryption:
                  type: boolean
                opportunisticOnion:
                  type: boolean
                originErrorPagePassThru:
                  type: boolean
                polish:
                  type: boolean
                prefetchPreload:
                  type: boolean
                privacyPass:
                  type: boolean
                responseBuffering:
                  type: boolean
                rocketLoader:
                  type: boolean
                webp:
                  type: boolean
              type: object
          required:
          - apiToken
          type: object
        status:
          description: ZoneStatus defines the observed state of Zone
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
